apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: developer-getting-started
  description: A sample catalog to help developers get started with TAP
  annotations:
    'backstage.io/techdocs-ref': dir:.
    'backstage.tanzu.vmware.com/group.default.root': 'catalog.entity.read'
  links:
    - url: https://www.example.com
      title: 'TAP Information'
      icon: locallibrary
spec:
  owner: root

---

apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: team-b-documentation
  description: A sample catalog to help developers get started with TAP
  annotations:
    'backstage.io/techdocs-ref': dir:.
    'backstage.tanzu.vmware.com/group.default.team-b': 'catalog.entity.read,catalog.entity.update,catalog.entity.delete'
  links:
    - url: https://www.example.com
      title: 'TAP Information'
      icon: locallibrary
spec:
  owner: team-b

---

apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: team-a-documentation
  description: A sample catalog to help developers get started with TAP
  annotations:
    'backstage.io/techdocs-ref': dir:.
    'backstage.tanzu.vmware.com/group.default.team-a': 'catalog.entity.read'
  links:
    - url: https://www.example.com
      title: 'TAP Information'
      icon: locallibrary
spec:
  owner: rabeyta
